version: "3"

services:
  reverse-proxy:
    image: ghcr.io/clochette-absinthe/reverse-proxy:latest
    container_name: clochette-reverse-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    volumes:
      - ./certbot-ssl/:/var/www/certbot/ssl/:ro

  frontend:
    image: ghcr.io/clochette-absinthe/frontend:latest
    container_name: clochette-frontend
    expose:
      - 3000
    environment:
      - SECRET_KEY=${JWT_SECRET_KEY}
    command:
      [
        "pm2-runtime",
        "start",
        "npm",
        "--name",
        "clochette-frontend",
        "--",
        "start"
      ]

  backend:
    depends_on:
      - database
    image: ghcr.io/clochette-absinthe/backend:latest
    container_name: clochette-backend
    expose:
      - 8080
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]
    environment:
      - POSTGRES_HOST=clochette-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=clochette
      - POSTGRES_USER=clochette
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MIGRATE=${MIGRATE}
      - ALERT_BACKEND=github # Default is terminal if not set
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ISSUE_LABELS=Backend,bug,bot
      - REPOSITORY_NAME=${REPOSITORY_NAME}
      - REPOSITORY_OWNER=${REPOSITORY_OWNER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BASE_ACCOUNT_USERNAME=${BASE_ACCOUNT_USERNAME} # Default is admin if not set
      - BASE_ACCOUNT_PASSWORD=${BASE_ACCOUNT_PASSWORD}
      - LOCALE=${LOCALE}

  database:
    image: postgres:14.5-alpine
    container_name: clochette-db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=clochette
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=clochette
