repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.4
    hooks:
      # Run the linter.
      - id: ruff
        args:
          [
            backend/app,
            --fix,
            --exclude,
            backend/app/plugins,
            --exclude,
            backend/alembic,
          ]
      # Run the formatter.
      - id: ruff-format
        args:
          [
            backend/app,
            --exclude,
            backend/app/plugins,
            --exclude,
            backend/alembic,
          ]
