#version: "1.0.0"
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
    container_name: clochette-frontend
    ports:
      - "443:443"
      - "80:80"

  backend:
    depends_on:
      - database
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    container_name: clochette-backend
    ports:
      - "8080:80"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    environment:
      - POSTGRES_HOST=clochette-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=clochette
      - POSTGRES_USER=clochette
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- MIGRATE=True
  
  database:
    image: postgres:14.5-alpine
    container_name: clochette-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clochette
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=clochette