
/**
 * Generated by @openapi-codegen
 *
 */

export const patchedRoutes = [
  {
    "path": "/api/v1/auth/login/",
    "method": "post"
  }
];
export const unprotectedRoutes = [
  {
    "path": "/api/v1/",
    "method": "get"
  },
  {
    "path": "/api/v1/health",
    "method": "get"
  },
  {
    "path": "/api/v1/error",
    "method": "get"
  },
  {
    "path": "/api/v1/version",
    "method": "get"
  },
  {
    "path": "/api/v1/account/",
    "method": "post"
  },
  {
    "path": "/api/v1/auth/login/",
    "method": "post"
  }
];
