version: "3"

services:
  reverse-proxy:
    build:
      context: ../..
      dockerfile: ./docker/clochette-dev/reverse-proxy/Dockerfile
    container_name: clochette-reverse-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ../..
      dockerfile: ./docker/clochette-dev/frontend/Dockerfile
    container_name: clochette-frontend
    ports:
      - 8300:3000
    environment:
      - SECRET_KEY=${JWT_SECRET_KEY}
    command:
      [
        "pm2-runtime",
        "start",
        "npm",
        "--name",
        "clochette-frontend",
        "--",
        "start"
      ]

  backend:
    depends_on:
      - database
    build:
      context: ../..
      dockerfile: ./docker/clochette-dev/backend/Dockerfile
    container_name: clochette-backend
    ports:
      - "8080:80"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]
    environment:
      - POSTGRES_HOST=clochette-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=clochette
      - POSTGRES_USER=clochette
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MIGRATE=${MIGRATE}
      - ALERT_BACKEND=github # Default is terminal if not set
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ISSUE_LABELS=Backend,bug,bot
      - REPOSITORY_NAME=${REPOSITORY_NAME}
      - REPOSITORY_OWNER=${REPOSITORY_OWNER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BASE_ACCOUNT_USERNAME=${BASE_ACCOUNT_USERNAME} # Default is admin if not set
      - BASE_ACCOUNT_PASSWORD=${BASE_ACCOUNT_PASSWORD}
      - LOCALE=${LOCALE}

  database:
    image: postgres:14.5-alpine
    container_name: clochette-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clochette
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=clochette
