# This workflow aims to build and push Docker-Compose images to the GitHub Container registry when a new release is published.

name: Build and push Docker images

on:
  push:
    branches: [ 'main' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    #needs: [ release-on-push ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker-Compose images
        run: docker-compose -f docker/docker-compose.yml build && docker-compose -f docker/docker-compose.yml push