name: Frontend Checks

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

defaults:
  run:
    working-directory: frontend

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache-dependency-path: frontend/package-lock.json
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify lint
        run: npm run lint

      - name: Verify format
        run: npm run format -- -c

      - name: Test frontend and get coverage
        run: npm run coverage

      - name: Save coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-frontend
          path: ./frontend/coverage/coverage-final.json

  coverage:
    needs: frontend-checks
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report-frontend
          path: ./frontend/coverage

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./frontend/coverage/coverage-final.json
          flags: frontend
